import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/home/header";
import { poppins } from "@/components/ui/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased pb-32`}>
        <Header />
        <main className="mt-20">{children}</main>
      </body>
    </html>
  );
}
